### PR TITLE
Import color badge component

### PR DESCRIPTION
**Pull request by quynhnguyen68**
## What?
Import `mt-color-badge` component

## Why?
Missing importing  `mt-color-badge` component and its Storybook stories

## How?
Import  `mt-color-badge` component  and create its Storybook stories

### CODE REVIEW

**Review by Haberkamp — CHANGES_REQUESTED** [review]
Hey, thanks for the PR! Two things: could you fill out the PR description completely and also create a changelog as described in our [contribution guidelines](https://github.com/shopware/meteor/blob/main/CONTRIBUTING.md)?

**Comment by quynhnguyen68** [comment]
> Additionally, it makes sense to create a handful Storybook Stories for that component with the different possible states.

Thank you, I will add Storybook and changelog

**Comment by quynhnguyen68** [comment]
> Additionally, it makes sense to create a handful Storybook Stories for that component with the different possible states.

@Haberkamp I already add Storybook stories and changelog, please help me take a look, thank you so much

**Comment by Haberkamp** [comment]
I'll close this issue because the color badge component is not intended to be used outside the library, as of now.

**Pull request closed without merging**
