### PR TITLE
NTR - Fix tooltip placement

### PR DESCRIPTION
**Pull request by sydinh**
## What?

A fix for this issue: https://github.com/shopware/meteor/issues/152

## Why?

It's a 🐛 

## How?

Set the tooltip's position to fixed, so the tooltip will always stay in the same place in the viewport, even if the page is scrolled.

## Testing?

N/A

## Screenshots (optional)

N/A

## Anything Else?

N/A

### CODE REVIEW

**Comment by sydinh** [comment]
I do not know why the visual tests failed, but I hope somebody can help me 🥺

**Comment by seggewiss** [comment]
> I do not know why the visual tests failed, but I hope somebody can help me 🥺

Looks like a pipeline issue 🤷 I've restarted the jobs

**Comment by sydinh** [comment]
> @sydinh I still can reproduce the issue on my machine.

Just send me the issue recording when you have time 😉

**Comment by Haberkamp** [comment]
@sydinh the issue I was able to produce was actually a different one. I'll approve your change.

**Review by Haberkamp — APPROVED** [review]

**Pull request merged**
