### PR TITLE
Allow select a range of datepicker

### PR DESCRIPTION
**Pull request by nguyenquocdaile**
In the new topic, we are implementing. It has an awesome feature of flatpickr is a select range date.
I think we need to support it.

https://flatpickr.js.org/examples/#range-calendar

### CODE REVIEW

**Review by Haberkamp — CHANGES_REQUESTED** [review]
Please create a new story that includes the range version of the date picker

**Comment by nguyenquocdaile** [comment]
> Please create a new story that includes the range version of the date picker

Hi Is there something else I can improve here?

**Comment by Haberkamp** [comment]
> > Please create a new story that includes the range version of the date picker
> 
> Hi Is there something else I can improve here?

Would be great if the component makes use of the design tokens. You could talk to @fabianhueske about further questions.

**Comment by nguyenquocdaile** [comment]
> > > Please create a new story that includes the range version of the date picker
> > 
> > 
> > Hi Is there something else I can improve here?
> 
> Would be great if the component makes use of the design tokens. You could talk to @fabianhueske about further questions.

Ok, it takes time to apply the new style. I'm working on it

**Comment by nguyenquocdaile** [comment]
> > > > Please create a new story that includes the range version of the date picker
> > > 
> > > 
> > > Hi Is there something else I can improve here?
> > 
> > 
> > Would be great if the component makes use of the design tokens. You could talk to @fabianhueske about further questions.
> 
> Ok, it takes time to apply the new style. I'm working on it

Hi @Haberkamp , storybook test is failing. Because it does not match with the snapshot. Do you know any way to generate a snapshot to pass the test?

**Comment by nguyenquocdaile** [comment]
Hi @Haberkamp , Could you help me check the pipeline here? The test is passed in the local but I don't know why it's failed here 😭

**Comment by nguyenquocdaile** [comment]
> > > > Please create a new story that includes the range version of the date picker
> > > 
> > > 
> > > Hi Is there something else I can improve here?
> > 
> > 
> > Would be great if the component makes use of the design tokens. You could talk to @fabianhueske about further questions.
> 
> Ok, it takes time to apply the new style. I'm working on it

Hi @Haberkamp, Please help me check it

**Pull request closed without merging**
